// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: central/v1/central.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListVideosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_central_v1_central_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_central_v1_central_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_central_v1_central_proto_rawDescGZIP(), []int{0}
}

type ListVideosReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*VideoMeta `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *ListVideosReply) Reset() {
	*x = ListVideosReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_central_v1_central_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVideosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosReply) ProtoMessage() {}

func (x *ListVideosReply) ProtoReflect() protoreflect.Message {
	mi := &file_central_v1_central_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosReply.ProtoReflect.Descriptor instead.
func (*ListVideosReply) Descriptor() ([]byte, []int) {
	return file_central_v1_central_proto_rawDescGZIP(), []int{1}
}

func (x *ListVideosReply) GetVideos() []*VideoMeta {
	if x != nil {
		return x.Videos
	}
	return nil
}

type GetVideoInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetVideoInfoRequest) Reset() {
	*x = GetVideoInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_central_v1_central_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoRequest) ProtoMessage() {}

func (x *GetVideoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_central_v1_central_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoInfoRequest) Descriptor() ([]byte, []int) {
	return file_central_v1_central_proto_rawDescGZIP(), []int{2}
}

func (x *GetVideoInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVideoInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Video *VideoMeta `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *GetVideoInfoReply) Reset() {
	*x = GetVideoInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_central_v1_central_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoReply) ProtoMessage() {}

func (x *GetVideoInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_central_v1_central_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoReply.ProtoReflect.Descriptor instead.
func (*GetVideoInfoReply) Descriptor() ([]byte, []int) {
	return file_central_v1_central_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoInfoReply) GetVideo() *VideoMeta {
	if x != nil {
		return x.Video
	}
	return nil
}

type VideoMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Path      string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size      int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Thumbnail string `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	NodeAddr  string `protobuf:"bytes,6,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"` // 记录视频在哪个节点
	IsPublic  bool   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
}

func (x *VideoMeta) Reset() {
	*x = VideoMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_central_v1_central_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMeta) ProtoMessage() {}

func (x *VideoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_central_v1_central_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMeta.ProtoReflect.Descriptor instead.
func (*VideoMeta) Descriptor() ([]byte, []int) {
	return file_central_v1_central_proto_rawDescGZIP(), []int{4}
}

func (x *VideoMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VideoMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VideoMeta) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *VideoMeta) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

func (x *VideoMeta) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

var File_central_v1_central_proto protoreflect.FileDescriptor

var file_central_v1_central_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x65, 0x6e,
	0x74, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x65, 0x6e, 0x74,
	0x72, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d,
	0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x25, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x32, 0xaa, 0x01, 0x0a, 0x0e, 0x43,
	0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x12, 0x1d, 0x2e, 0x63, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x65, 0x6e,
	0x74, 0x72, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_central_v1_central_proto_rawDescOnce sync.Once
	file_central_v1_central_proto_rawDescData = file_central_v1_central_proto_rawDesc
)

func file_central_v1_central_proto_rawDescGZIP() []byte {
	file_central_v1_central_proto_rawDescOnce.Do(func() {
		file_central_v1_central_proto_rawDescData = protoimpl.X.CompressGZIP(file_central_v1_central_proto_rawDescData)
	})
	return file_central_v1_central_proto_rawDescData
}

var file_central_v1_central_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_central_v1_central_proto_goTypes = []any{
	(*ListVideosRequest)(nil),   // 0: central.v1.ListVideosRequest
	(*ListVideosReply)(nil),     // 1: central.v1.ListVideosReply
	(*GetVideoInfoRequest)(nil), // 2: central.v1.GetVideoInfoRequest
	(*GetVideoInfoReply)(nil),   // 3: central.v1.GetVideoInfoReply
	(*VideoMeta)(nil),           // 4: central.v1.VideoMeta
}
var file_central_v1_central_proto_depIdxs = []int32{
	4, // 0: central.v1.ListVideosReply.videos:type_name -> central.v1.VideoMeta
	4, // 1: central.v1.GetVideoInfoReply.video:type_name -> central.v1.VideoMeta
	0, // 2: central.v1.CentralService.ListVideos:input_type -> central.v1.ListVideosRequest
	2, // 3: central.v1.CentralService.GetVideoInfo:input_type -> central.v1.GetVideoInfoRequest
	1, // 4: central.v1.CentralService.ListVideos:output_type -> central.v1.ListVideosReply
	3, // 5: central.v1.CentralService.GetVideoInfo:output_type -> central.v1.GetVideoInfoReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_central_v1_central_proto_init() }
func file_central_v1_central_proto_init() {
	if File_central_v1_central_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_central_v1_central_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListVideosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_central_v1_central_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListVideosReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_central_v1_central_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetVideoInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_central_v1_central_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetVideoInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_central_v1_central_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*VideoMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_central_v1_central_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_central_v1_central_proto_goTypes,
		DependencyIndexes: file_central_v1_central_proto_depIdxs,
		MessageInfos:      file_central_v1_central_proto_msgTypes,
	}.Build()
	File_central_v1_central_proto = out.File
	file_central_v1_central_proto_rawDesc = nil
	file_central_v1_central_proto_goTypes = nil
	file_central_v1_central_proto_depIdxs = nil
}
