// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"videoCluster/internal/biz"
	"videoCluster/internal/conf"
	"videoCluster/internal/consul"
	"videoCluster/internal/data"
	"videoCluster/internal/node/server"
	"videoCluster/internal/node/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewBadgerDB(confServer)
	if err != nil {
		return nil, nil, err
	}
	videoVideoRepository := data.NewVideoVideoRepository(db)
	videoUsecase := biz.NewVideoUsecase(videoVideoRepository)
	videoService := service.NewVideoService(videoUsecase)
	grpcServer := server.NewGRPCServer(confServer, videoService, logger)
	httpServer := server.NewHTTPServer(confServer, videoService, logger)
	client, err := consul.NewConsulClient(confData)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, client)
	return app, func() {
	}, nil
}
